vich_uploader:
    db_driver: orm

    mappings:
        picture:
            uri_prefix: '%images%'
            upload_destination: '%kernel.project_dir%/public/build/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
